GET http://localhost:8080/api/invoices HTTP/1.1

###
POST http://localhost:8080/api/invoices HTTP/1.1
Content-Type: application/json

{
    "name": "Nicolas",
    "products": "Sandias",
    "IVA": "12",
    "total": "20"
}


###
GET http://localhost:8080/api/invoices/ HTTP/1.1

###
DELETE http://localhost:8080/api/invoices/ HTTP/1.1

PUT http://localhost:8080/api/invoices/ HTTP/1.1
Content-Type: application/json

{
    "name": "Pedro",
    "products": "Peras",
    "IVA": "12",
    "total": "100"
}