###
GET http://localhost:8080/api/products HTTP/1.1

###
POST http://localhost:8080/api/products HTTP/1.1
Content-Type: application/json

{
    "name": "Mandarinas",
    "description": "Fruta Clemenules",
    "provider": "62c8db5a810b2e0578120bbb",
    "price": 0.25,
    "quantity":10
}

###
GET http://localhost:8080/api/products/62b28cf602a5a4e280c2165b HTTP/1.1

###
DELETE http://localhost:8080/api/products/62ca102cbdc36d1cb3dc1c6e HTTP/1.1

###
PUT http://localhost:8080/api/products/62ba059c0a1ba57990610445 HTTP/1.1
Content-Type: application/json

{
    "name": "Mandarinas",
    "description": "Fruta",
    "provider": "62c8db5a810b2e0578120bbb",
    "price": 0.40,
    "quantity": 5 
}