###
GET http://localhost:8080/api/providers HTTP/1.1

###
POST http://localhost:8080/api/providers HTTP/1.1
Content-Type: application/json

{
    "name_provider": "Ananke",
    "city": "Quito"
}

###
GET http://localhost:8080/api/providers/62c8da529fd7dff75b59cae2 HTTP/1.1

###
DELETE http://localhost:8080/api/providers/62d102d9d65ca9956e4961ea HTTP/1.1